// 术语库标签映射：source → tags[]
// tags: "common"=通用注入, 产品线ID=该产品线专属
// 由 scripts/convert-glossary-tags.js 自动生成，不要手动编辑
export const GLOSSARY_TAG_MAP: Record<string, string[]> = {
  "1GB = 1 billion bytes; actual system capacity may differ": ["common"],
  "4X Faster than USB 3.0": ["portable_storage"],
  "AMD EXPO": ["gaming_dimm"],
  "ARES Memory Series": ["gaming_dimm"],
  "Action Cam": ["consumer_cards"],
  "Auto-Backup with the Lexar App": ["common"],
  "Backward Compatible": ["common"],
  "CAS Latency": ["gaming_dimm"],
  "CFexpress™ Type A": ["professional_imaging"],
  "CFexpress™ Type B": ["professional_imaging"],
  "Capture the Diamond Moments": ["professional_imaging"],
  "Card Reader": ["portable_storage"],
  "Compact & Portable": ["portable_storage"],
  "DDR5 CUDIMM": ["pc_productivity"],
  "DDR5 Performance with Powerful Heatsink": ["gaming_dimm"],
  "DRAM Cache": ["pc_productivity"],
  "Desktop Backup Dock": ["portable_storage"],
  "Desktop Memory": ["pc_productivity"],
  "Drones": ["consumer_cards"],
  "Drop proof": ["portable_storage"],
  "Dynamic SLC Caching": ["pc_productivity"],
  "End Storage Anxiety": ["common"],
  "Frame Drop": ["common"],
  "Full Game Library Storage": ["gaming_ssd"],
  "Handheld Console Memory Card": ["gaming_card"],
  "Handheld Consoles": ["gaming_card"],
  "Heat-Defying 6nm Controller": ["pc_productivity"],
  "Heatsink": ["common"],
  "IPx7 Water proof": ["portable_storage"],
  "Impact proof": ["portable_storage"],
  "Intel XMP 3.0": ["gaming_dimm"],
  "Key Ring Loop": ["portable_storage"],
  "LPDDR5X": ["pc_productivity"],
  "Laptop Memory": ["pc_productivity"],
  "Lexar 2.5 Inch Hard Drive Enclosure": ["portable_storage"],
  "Lexar ARES DDR4 Desktop Memory": ["gaming_dimm"],
  "Lexar ARES DDR5 OC Desktop Memory": ["gaming_dimm"],
  "Lexar ARES PRO M.2 2280 PCIe 5.0 NVMe SSD": ["gaming_ssd"],
  "Lexar ARES RGB 2nd Gen DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar ARES RGB DDR4 Desktop Memory": ["gaming_dimm"],
  "Lexar ARES RGB DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar ARMOR 700 Portable SSD": ["portable_storage"],
  "Lexar ARMOR GOLD SDXC UHS-II Card": ["professional_imaging"],
  "Lexar ARMOR SILVER PRO SDXC UHS-II Card": ["professional_imaging"],
  "Lexar Air Portable SSD": ["portable_storage"],
  "Lexar Air Portable SSD Elite Legends Series": ["portable_storage"],
  "Lexar App": ["common"],
  "Lexar BLUE PLUS microSDHC/microSDXC UHS-I Card": ["consumer_cards"],
  "Lexar BLUE microSDXC UHS-I Card": ["consumer_cards"],
  "Lexar CFexpress Type A USB-C Reader": ["portable_storage"],
  "Lexar CFexpress Type B USB-C Reader": ["portable_storage"],
  "Lexar DDR4 SODIMM Laptop Memory": ["pc_productivity"],
  "Lexar DDR4 UDIMM Desktop Memory": ["pc_productivity"],
  "Lexar DDR5 SODIMM Laptop Memory": ["pc_productivity"],
  "Lexar DDR5 UDIMM Desktop Memory": ["pc_productivity"],
  "Lexar DataShield": ["common"],
  "Lexar DiskMaster": ["common"],
  "Lexar Dual Drive Portable SSD D70E": ["portable_storage"],
  "Lexar Dual-Slot USB-A Reader": ["portable_storage"],
  "Lexar Dual-Slot USB-A/C Reader": ["portable_storage"],
  "Lexar E300 M.2 SSD Enclosure": ["portable_storage"],
  "Lexar E6 M.2 SSD Enclosure": ["portable_storage"],
  "Lexar EQ790 M.2 2280 PCIe Gen4x4 NVMe SSD": ["pc_productivity"],
  "Lexar EQ790 with Heatsink M.2 2280 PCIe Gen4x4 NVMe SSD": ["pc_productivity"],
  "Lexar ES3 Portable SSD": ["portable_storage"],
  "Lexar ES4 Portable SSD with Magnetic Set": ["portable_storage"],
  "Lexar ES5 Magnetic Portable SSD": ["portable_storage"],
  "Lexar H31 7-in-1 USB-C Hub": ["portable_storage"],
  "Lexar High-Endurance microSDHC/microSDXC UHS-I Card": ["consumer_cards"],
  "Lexar High-Performance 633x microSDHC/microSDXC UHS-I Card BLUE Series": ["consumer_cards"],
  "Lexar High-Performance 800x PRO SDHC/SDXC UHS-I Card BLUE Series": ["professional_imaging"],
  "Lexar JumpDrive  Solid State Dual Drive D500 USB 3.2 Gen 1 Type-C": ["portable_storage"],
  "Lexar JumpDrive A30E USB 3.2 Gen 1 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive Dual Drive D300 USB 3.2 Gen 1 Type-C": ["portable_storage"],
  "Lexar JumpDrive Dual Drive D35c USB 3.0 Type-C": ["portable_storage"],
  "Lexar JumpDrive Dual Drive D400 USB 3.2 Type-C": ["portable_storage"],
  "Lexar JumpDrive Dual Drive D40E USB 3.2 Gen 1 Type-C": ["portable_storage"],
  "Lexar JumpDrive Dual Drive E32c USB 3.2 Gen1 Type-C": ["portable_storage"],
  "Lexar JumpDrive E21 USB 2.0 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive E31 USB 3.0 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive Fingerprint F35 PRO USB 3.2 Gen 1 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive M22 USB Flash Drive": ["portable_storage"],
  "Lexar JumpDrive M400 USB 3.2 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive M900 USB 3.1 Flash Drive (EOL)": ["portable_storage"],
  "Lexar JumpDrive P30 USB 3.2 Gen 1 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive S47 USB 3.2 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive S57 USB 3.0 Flash Drive (EOL)": ["portable_storage"],
  "Lexar JumpDrive S80 USB 3.2 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive Solid State Dual Drive D50E USB 3.2 Gen 1 Type-C": ["portable_storage"],
  "Lexar JumpDrive TwistTurn2 USB Flash Drive": ["portable_storage"],
  "Lexar JumpDrive V100 USB 3.2 Flash Drive": ["portable_storage"],
  "Lexar JumpDrive V40 USB Flash Drive": ["portable_storage"],
  "Lexar JumpDrive V400 USB 3.2 Flash Drive": ["portable_storage"],
  "Lexar JumpDriveS60 USB Flash Drive": ["portable_storage"],
  "Lexar Multi-Card 2-in-1 USB 3.1 Reader": ["portable_storage"],
  "Lexar NM Card": ["consumer_cards"],
  "Lexar NM100 M.2 2280 SATA III (6Gb/s) SSD": ["pc_productivity"],
  "Lexar NM610PRO M.2 2280 PCIe Gen3x4 NVMe SSD": ["pc_productivity"],
  "Lexar NM620 M.2 2280 NVMe SSD": ["pc_productivity"],
  "Lexar NM710 M.2 2280 PCIe Gen4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NM790 M.2 2280 PCIe Gen 4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NM790 with Heatsink M.2 2280 PCIe Gen 4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NM970 M.2 2280 PCIe 5.0 NVMe SSD": ["pc_productivity"],
  "Lexar NM990 M.2 2280 PCIe 5.0 NVMe SSD": ["pc_productivity"],
  "Lexar NQ100 2.5\" SATA III (6Gb/s) SSD": ["pc_productivity"],
  "Lexar NQ700 M.2 2280 PCIe Gen4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NQ710 NVMe PCIe 4.0 SSD": ["pc_productivity"],
  "Lexar NQ780 M.2 2280 PCIe Gen 4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NQ790 M.2 2280 PCIe Gen4x4 NVMe SSD": ["pc_productivity"],
  "Lexar NS100 2.5\" SATA III (6Gb/s) SSD": ["pc_productivity"],
  "Lexar PLAY 2230 PCIe 4.0 SSD": ["gaming_ssd"],
  "Lexar PLAY 2280 PCIe 4.0 SSD": ["gaming_ssd"],
  "Lexar PLAY PRO microSDXC Express Card": ["gaming_card"],
  "Lexar PLAY X M.2 PCIe 4.0 NVMe SSD": ["gaming_ssd"],
  "Lexar PLAY microSDXC UHS-I Card": ["gaming_card"],
  "Lexar Professional 1066x SDXC UHS-I Card SILVER Series": ["professional_imaging"],
  "Lexar Professional 1066x microSDXC UHS-I Card SILVER Series": ["professional_imaging"],
  "Lexar Professional 1667x SDXC UHS-II Card  SILVER Series": ["professional_imaging"],
  "Lexar Professional 1800x SDXC UHS-II Card GOLD Series": ["professional_imaging"],
  "Lexar Professional 2000x SDXC UHS-II Card GOLD Series": ["professional_imaging"],
  "Lexar Professional CFexpress Type A / SD USB 3.2 Gen 2 Reader": ["portable_storage"],
  "Lexar Professional CFexpress Type A Card GOLD Series": ["professional_imaging"],
  "Lexar Professional CFexpress Type A Card SILVER Series": ["professional_imaging"],
  "Lexar Professional CFexpress Type B / SD USB 3.2 Gen 2 Reader": ["portable_storage"],
  "Lexar Professional CFexpress Type B Card GOLD Series": ["professional_imaging"],
  "Lexar Professional CFexpress Type B Card SILVER Series": ["professional_imaging"],
  "Lexar Professional CFexpress Type B USB 3.2 Gen 2x2 Reader": ["portable_storage"],
  "Lexar Professional Cfexpress TypeB Card DIAMOND Series": ["professional_imaging"],
  "Lexar Professional DIAMOND CFexpress 4.0 Type B Card": ["professional_imaging"],
  "Lexar Professional GOLD CFexpress 4.0 Type A Card": ["professional_imaging"],
  "Lexar Professional GOLD CFexpress 4.0 Type B Card": ["professional_imaging"],
  "Lexar Professional GOLD microSDXC UHS-II Card": ["professional_imaging"],
  "Lexar Professional Go Portable SSD": ["portable_storage"],
  "Lexar Professional Go Portable SSD with Hub": ["portable_storage"],
  "Lexar Professional Multi-Card 3-in-1 USB 3.1 Reader": ["portable_storage"],
  "Lexar Professional NM1090 PRO PCIe 5.0 NVMe M.2 2280 SSD": ["pc_productivity"],
  "Lexar Professional SILVER CFexpress  4.0 Type A Card": ["professional_imaging"],
  "Lexar Professional SILVER CFexpress 4.0 Type B Card": ["professional_imaging"],
  "Lexar Professional SILVER PLUS SDXC UHS-I Card": ["professional_imaging"],
  "Lexar Professional SILVER PLUS microSDXC UHS-I Card": ["professional_imaging"],
  "Lexar Professional SILVER PRO SDXC UHS-II Card": ["professional_imaging"],
  "Lexar Professional SILVER SDXC UHS-I Card": ["professional_imaging"],
  "Lexar Professional SILVER microSDXC UHS-I Card": ["professional_imaging"],
  "Lexar Professional SL600 Portable SSD": ["portable_storage"],
  "Lexar Professional USB 4 SSD Enclosure": ["portable_storage"],
  "Lexar Professional USB-C Dual-Slot Reader": ["portable_storage"],
  "Lexar Professional Workflow": ["portable_storage"],
  "Lexar Professional Workflow CFexpress 4.0 Type A Card Reader": ["portable_storage"],
  "Lexar Professional Workflow CFexpress 4.0 Type B Card Reader": ["portable_storage"],
  "Lexar Professional Workflow Dual-Slot SD UHS-II Card Reader": ["portable_storage"],
  "Lexar Professional Workflow Go": ["portable_storage"],
  "Lexar Professional Workflow Portable SSD": ["portable_storage"],
  "Lexar Professional Workflow SD/Micro SD UHS-II Card Reader": ["portable_storage"],
  "Lexar Quality Labs": ["common"],
  "Lexar RGB Sync": ["gaming_dimm"],
  "Lexar Recovery Tool": ["common"],
  "Lexar SDHC/SDXC UHS-I Card E-series": ["consumer_cards"],
  "Lexar SL200 Portable SSD": ["portable_storage"],
  "Lexar SL210 Portable SSD (EOL)": ["portable_storage"],
  "Lexar SL300 Portable SSD": ["portable_storage"],
  "Lexar SL500 Portable SSD": ["portable_storage"],
  "Lexar SL500 Portable SSD Elite Legends Series": ["portable_storage"],
  "Lexar SL500 Portable SSD with Magnetic Set": ["portable_storage"],
  "Lexar SL660 BLAZE Gaming Portable SSD (EOL)": ["portable_storage"],
  "Lexar SSD Dash": ["pc_productivity"],
  "Lexar Solid State Dual Drive D500 USB 3.2 Gen 1 Type-C Elite Legends Series": ["portable_storage"],
  "Lexar THOR 2nd Gen DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar THOR DDR4 UDIMM Desktop Memory": ["gaming_dimm"],
  "Lexar THOR OC DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar THOR PRO PCIe Gen4X4 NVMe SSD": ["gaming_ssd"],
  "Lexar THOR RGB 2nd Gen DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar THOR RGB DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar THOR Z DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar THOR Z RGB DDR5 Desktop Memory": ["gaming_dimm"],
  "Lexar TouchLock Portable SSD": ["portable_storage"],
  "Lexar logo": ["common"],
  "Lexar microSD/SD USB-A/C Card Reader": ["portable_storage"],
  "Lexar microSDHC/microSDXC UHS-I Card E-Series": ["consumer_cards"],
  "Lexar microSDXC Express Card Reader": ["portable_storage"],
  "Lexar microSDXC UHS-I Card E-Series Plus": ["consumer_cards"],
  "Lexar nCARD NM card 2-in-1 USB 3.1 Reader": ["consumer_cards"],
  "Lexar product designs": ["common"],
  "Lexar products": ["common"],
  "Limited Lifetime Warranty": ["common"],
  "Limited warranty for non-artificial damage": ["common"],
  "Longsys": ["common"],
  "MTBF": ["common"],
  "Magnet proof": ["portable_storage"],
  "NVMe 2.0": ["pc_productivity"],
  "No dropped frames": ["professional_imaging"],
  "No sudden speed drop": ["professional_imaging"],
  "On-die ECC": ["common"],
  "PCIe 3.0": ["common"],
  "PCIe 4.0": ["common"],
  "PCIe 5.0": ["common"],
  "PCIe Gen 4x4": ["common"],
  "PCIe Gen3x4": ["common"],
  "PCIe Gen5x4": ["common"],
  "Play Hard, Work Hard": ["common"],
  "Please back up important data properly": ["common"],
  "Plug and Play": ["common"],
  "Portable SSD": ["portable_storage"],
  "Power Up Your Play": ["gaming_ssd"],
  "Product images are for reference only": ["common"],
  "Professional Grade Performance": ["professional_imaging"],
  "Protect Your Files with Lexar DataShield": ["common"],
  "Random Read/Write": ["common"],
  "Read Speed": ["common"],
  "Rigorously Tested": ["common"],
  "SD Memory Card": ["common"],
  "SLC Cache": ["common"],
  "SSD Enclosure": ["portable_storage"],
  "Seamless Compatibility": ["common"],
  "Seamless Play, Ultimate Gaming": ["gaming_ssd"],
  "Seamlessly compatible with Intel XMP 3.0 & AMD EXPO for one-click overclocking.": ["gaming_dimm"],
  "Shock & Drop Resistant": ["portable_storage"],
  "Shock proof": ["portable_storage"],
  "Smooth 4K Video Recording": ["professional_imaging"],
  "Solid State Flash Drive": ["portable_storage"],
  "Speed Drop": ["common"],
  "Stable & Reliable": ["common"],
  "Steel-Armored, Unstoppable Performance": ["professional_imaging"],
  "Sustained Read/Write": ["common"],
  "TBW": ["pc_productivity"],
  "THOR DDR5 RGB": ["gaming_dimm"],
  "THOR Memory Series": ["gaming_dimm"],
  "TLC NAND": ["common"],
  "Tablets": ["common"],
  "Temperature Resistant": ["common"],
  "Temperature proof": ["common"],
  "Transfer speeds may vary by device and environment": ["common"],
  "Type-C": ["common"],
  "UHS-II": ["consumer_cards"],
  "USB 3.2": ["common"],
  "USB Flash Drive": ["portable_storage"],
  "USB Hub": ["portable_storage"],
  "Unleash Your Computer with Next-Gen DDR5": ["gaming_dimm"],
  "Unleash Your Full Potential in Work and Play": ["common"],
  "Unlock Device Potential": ["common"],
  "Unmatched Performance": ["common"],
  "Wear Leveling": ["common"],
  "Wear out proof": ["consumer_cards"],
  "Wide Compatibility": ["common"],
  "Write Speed": ["common"],
  "X-ray proof": ["common"],
  "Zero Lag Game Loading": ["gaming_ssd"],
  "microSD Memory Card": ["common"],
};
